
export const data =[{
    id: "2",
    first_name: "Traci",
    last_name: "Brisland",
    email: "tbrisland1@howstuffworks.com",
    gender: "Female",
    username: "tbrisland1",
    src: "https://i.pravatar.cc/300?random=1"
  }, {
    id: "3",
    first_name: "Doroteya",
    last_name: "Koene",
    email: "dkoene2@amazon.co.uk",
    gender: "Female",
    username: "dkoene2",
    src: "https://i.pravatar.cc/300?random=2"
  }, {
    id: "4",
    first_name: "Edeline",
    last_name: "Coxhell",
    email: "ecoxhell3@icio.us",
    gender: "Male",
    username: "ecoxhell3",
    src: "https://i.pravatar.cc/300?random=3"
  }, {
    id: "5",
first_name: "Wye",
    last_name: "Peealess",
    email: "wpeealess4@wikipedia.org",
    gender: "Female",
    username: "wpeealess4",
    src: "https://i.pravatar.cc/300?random=4"
  }, {
    id: "6",
    first_name: "Jaye",
    last_name: "Vince",
    email: "jvince5@topsy.com",
    gender: "Female",
    username: "jvince5",
    src: "https://i.pravatar.cc/300?random=5"
  }, {
    id: "7",
    first_name: "Evvy",
    last_name: "Mordy",
    email: "emordy6@list-manage.com",
    gender: "Female",
    username: "emordy6",
    src: "https://i.pravatar.cc/300?random=6"
  }, {
    id: "8",
    first_name: "Suki",
    last_name: "Tarply",
    email: "starply7@nationalgeographic.com",
    gender: "Female",
    username: "starply7",
    src: "https://i.pravatar.cc/300?random=7"
  }, {
    id: "9",
    first_name: "Patrizia",
    last_name: "Berget",
    email: "pberget8@dion.ne.jp",
    gender: "Male",
    username: "pberget8",
    src: "https://i.pravatar.cc/300?random=8"
  }, {
    id: "10",
    first_name: "Willabella",
    last_name: "Loche",
    email: "wloche9@tinyurl.com",
    gender: "Male",
    username: "wloche9",
    src: "https://i.pravatar.cc/300?random=9"
  }, {
    id: "11",
    first_name: "Truda",
    last_name: "Rusk",
    email: "truska@mashable.com",
    gender: "Female",
    username: "truska",
    src: "https://i.pravatar.cc/300?random=10"
  }, {
    id: "12",
    first_name: "Josie",
    last_name: "Atchly",
    email: "jatchlyb@marriott.com",
    gender: "Female",
    username: "jatchlyb",
    src: "https://i.pravatar.cc/300?random=11"
  }, {
    id: "13",
    first_name: "Mattheus",
    last_name: "Broyd",
    email: "mbroydc@sciencedirect.com",
    gender: "Male",
    username: "mbroydc",
    src: "https://i.pravatar.cc/300?random=12"
  }, {
    id: "14",
    first_name: "Britt",
    last_name: "Itzkovwich",
    email: "bitzkovwichd@home.pl",
    gender: "Female",
    username: "bitzkovwichd",
    src: "https://i.pravatar.cc/300?random=13"
  }, {
    id: "15",
    first_name: "Roxy",
    last_name: "Elwood",
    email: "relwoode@hubpages.com",
    gender: "Male",
    username: "relwoode",
    src: "https://i.pravatar.cc/300?random=14"
  }]